In [113]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [114]:
# Load dataset

df = pd.read_csv(
    r"C:\Users\deore\Downloads\archive (2)\books.csv",
    on_bad_lines="skip"
)

In [3]:
# inspect the dataset

df.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.shape

(11123, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11123 entries, 0 to 11122
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              11123 non-null  int64
 1   title               11123 non-null  object
 2   authors             11123 non-null  object
 3   average_rating      11123 non-null  float64
 4   isbn                11123 non-null  object
 5   isbn13              11123 non-null  int64
 6   language_code       11123 non-null  object
 7     num_pages         11123 non-null  int64
 8   ratings_count       11123 non-null  int64
 9   text_reviews_count  11123 non-null  int64
 10  publication_date    11123 non-null  object
 11  publisher           11123 non-null  object
dtypes: float64(1), int64(5), object(6)
memory usage: 1.0+ MB

In [7]:
df.describe()

,bookID,average_rating,isbn13,num_pages,ratings_count,text_reviews_count
count,11123.000000,11123.000000,1.112300e+04,11123.000000,1.112300e+04,11123.000000
mean,21310.856963,3.934075,9.759880e+12,336.405556,1.794285e+04,542.048099
std,13094.727252,0.350485,4.429758e+11,241.152626,1.124992e+05,2576.619589
min,1.000000,0.000000,8.987060e+09,0.000000,0.000000e+00,0.000000
25%,10277.500000,3.770000,9.780345e+12,192.000000,1.040000e+02,9.000000
50%,20287.000000,3.960000,9.780582e+12,299.000000,7.450000e+02,47.000000
75%,32104.500000,4.140000,9.780872e+12,416.000000,5.000500e+03,238.000000
max,45641.000000,5.000000,9.790008e+12,6576.000000,4.597666e+06,94265.000000

In [8]:
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', '  num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='object')

In [9]:
# clean column names 

df.columns = df.columns.str.strip()
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', 'num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='object')

In [10]:
# check missing values

df.isnull().sum()

bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
num_pages             0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

In [11]:
# check missing values percentage in each column
(df.isnull().sum() / len(df) * 100).round(2)

bookID                0.0
title                 0.0
authors               0.0
average_rating        0.0
isbn                  0.0
isbn13                0.0
language_code         0.0
num_pages             0.0
ratings_count         0.0
text_reviews_count    0.0
publication_date      0.0
publisher             0.0
dtype: float64

In [12]:
df = df.copy()

# remove duplicate records

In [13]:
# count duplicates
df.duplicated().sum()

np.int64(0)

# title column

In [14]:
# count duplicate title in dataset
df["title"].duplicated().sum()

np.int64(775)

In [15]:
# print rows of duplicate title
df.loc[df["title"].duplicated(), "title"]

10       The Hitchhiker's Guide to the Galaxy (Hitchhik...
24       The Lord of the Rings (The Lord of the Rings  ...
37                                          The Changeling
40                                         The Known World
41                                         The Known World
                               ...
11075            Encuentro en el Ártico (Artemis Fowl  #2)
11076                      Artemis Fowl (Artemis Fowl  #1)
11078            The Subtle Knife (His Dark Materials  #2)
11080            The Subtle Knife (His Dark Materials  #2)
11096                                          On the Road
Name: title, Length: 775, dtype: object

In [16]:
#  see all duplicate titles
df[df["title"].duplicated(keep=False)]

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
9,14,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams,4.22,1400052920,9781400052929,eng,215,4930,460,8/3/2004,Crown
10,16,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams/Stephen Fry,4.22,0739322206,9780739322208,eng,6,1266,253,3/23/2005,Random House Audio
...,...,...,...,...,...,...,...,...,...,...,...,...
11075,45463,Encuentro en el Ártico (Artemis Fowl #2),Eoin Colfer/Ana Alcaina Pérez,3.95,0307343103,9780307343109,spa,320,15,3,7/5/2005,Montena
11076,45465,Artemis Fowl (Artemis Fowl #1),Eoin Colfer/Nathaniel Parker,3.84,1400085918,9781400085910,eng,6,55,14,4/6/2004,Listening Library
11078,45479,The Subtle Knife (His Dark Materials #2),Philip Pullman/Ian Beck,4.13,0375846727,9780375846724,eng,326,677,77,9/1/2007,Alfred A. Knopf Books for Young Readers
11080,45485,The Subtle Knife (His Dark Materials #2),Philip Pullman,4.13,0807210471,9780807210475,eng,8,39,8,1/28/2000,Listening Library
11096,45536,On the Road,Jack Kerouac/Ann Charters,3.63,0142437255,9780142437254,en-US,307,3271,342,1/3/2006,Penguin Classics

In [17]:
# remove duplicate rows and keep first
df = df.drop_duplicates("title",keep="first")

In [18]:
# check duplicates
df["title"].duplicated().sum()

np.int64(0)

In [19]:
# find the type of the title colum
df["title"].dtypes

dtype('O')

In [20]:
df = df.copy()

# authors column

In [21]:
# find type of author
df['authors'].dtypes

dtype('O')

In [22]:

df['authors'].isna().sum()

np.int64(0)

# rating column

In [23]:
# find type of rating 
df["average_rating"].dtypes

dtype('float64')

In [24]:
# check null values
df["average_rating"].isna().sum()

np.int64(0)

In [25]:
# check invalid ratings
i=df[
    (df["average_rating"] < 0) |
    (df["average_rating"] > 5)
]

i

Empty DataFrame
Columns: [bookID, title, authors, average_rating, isbn, isbn13, language_code, num_pages, ratings_count, text_reviews_count, publication_date, publisher]
Index: []

In [26]:
# find the min and max of the average_rating column
df["average_rating"].min(), df["average_rating"].max()

(0.0, 5.0)

In [27]:
df = df.copy()

# Publication date

In [28]:
# check the type of publication_date
df["publication_date"].dtypes

dtype('O')

In [29]:
# find the missing values
df["publication_date"].isna().sum()

np.int64(0)

In [30]:
df = df.copy()

In [31]:
# convert object to datetime format
df["publication_date"] = pd.to_datetime(
    df["publication_date"],
    errors = "coerce")

In [32]:
# create a separate year column
df["publication_year"] = df["publication_date"].dt.year

In [33]:
# check both columns
df[["publication_date","publication_year"]].head()

  publication_date  publication_year
0       2006-09-16            2006.0
1       2004-09-01            2004.0
2       2003-11-01            2003.0
3       2004-05-01            2004.0
4       2004-09-13            2004.0

In [34]:
# check type of publication_year
df["publication_year"].dtypes

dtype('float64')

In [35]:
# convert float to int
df["publication_year"]=df["publication_year"].astype("Int64")

In [36]:
# check the type
df["publication_year"].dtypes

Int64Dtype()

In [37]:
df["publication_year"].isnull().sum()

np.int64(2)

In [38]:
df = df.dropna(subset=["publication_year"])

In [39]:
df["publication_year"].dtypes

Int64Dtype()

In [40]:
df["publication_year"].isnull().sum()

np.int64(0)

In [41]:
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', 'num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher', 'publication_year'],
      dtype='object')

In [42]:
df =df.copy()

# author coloum

In [43]:
# find the type of author
df["authors"].dtypes

dtype('O')

In [44]:
# convert all values of authors coloumn into string type
df["authors"] = ( 
    df["authors"]
    .astype("string")
    .str.strip()
)

In [45]:
df["authors"].dtypes

string[python]

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10346 entries, 0 to 11122
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              10346 non-null  int64
 1   title               10346 non-null  object
 2   authors             10346 non-null  string
 3   average_rating      10346 non-null  float64
 4   isbn                10346 non-null  object
 5   isbn13              10346 non-null  int64
 6   language_code       10346 non-null  object
 7   num_pages           10346 non-null  int64
 8   ratings_count       10346 non-null  int64
 9   text_reviews_count  10346 non-null  int64
 10  publication_date    10346 non-null  datetime64[ns]
 11  publisher           10346 non-null  object
 12  publication_year    10346 non-null  Int64
dtypes: Int64(1), datetime64[ns](1), float64(1), int64(5), object(4), string(1)
memory usage: 1.1+ MB

In [47]:
df["authors"].value_counts()

authors
Rumiko Takahashi                                          39
P.G. Wodehouse                                            39
Orson Scott Card                                          33
Piers Anthony                                             30
Agatha Christie                                           30
                                                          ..
Hugh    Miller                                             1
Lonely Planet/Sarah Johnstone/Steve Fallon                 1
David Salo                                                 1
Rough Guides/Jan Dodd/Mark Lewis/Ron Emmons                1
William T. Vollmann/Larry McCaffery/Michael Hemmingson     1
Name: count, Length: 6295, dtype: Int64

# text_reviews_count  column

In [48]:
df["text_reviews_count"].dtypes

dtype('int64')

In [49]:
df["text_reviews_count"].isna().sum()

np.int64(0)

In [50]:
df["text_reviews_count"].head()

0    27591
1    29221
2      244
3    36325
4      164
Name: text_reviews_count, dtype: int64

In [51]:
df = df.copy()

# 


rename colums and drop columns

In [52]:
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', 'num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher', 'publication_year'],
      dtype='object')

In [53]:
df.rename(columns={"bookID":"Book_ID",
          "title":"Book_Title",
          "authors":"Authors",
          "average_rating":"Rating",
          "isbn":"ISBN-10",
          "isbn13":"ISBN-13",
          "num_pages":"Num_Of_Pages",
          "text_reviews_count":"Number_of_reviews",
          "publication_year":"Publication_year",
          "publisher":"Publisher",
          "language_code":"Language_Code",
          "ratings_count":"Ratings_Count",
                   
           
        
          },inplace = True)

In [54]:
df = df.copy()

In [55]:
df = df.copy()

# ISBN -10 column

In [56]:
df["ISBN-10"].duplicated().sum()

np.int64(0)

In [57]:

df["ISBN-10"].str.len().value_counts()

ISBN-10
10    10345
9         1
Name: count, dtype: int64

In [58]:
df = df[df["ISBN-10"].notna()].copy()

df["ISBN-10"] = df["ISBN-10"].astype("string").str.strip()

df = df[df["ISBN-10"].str.len() == 10].copy()

In [59]:

df["ISBN-10"].str.len().value_counts()

ISBN-10
10    10345
Name: count, dtype: Int64

# ISBN-13 colum

In [60]:
df["ISBN-10"].dtypes

string[python]

In [61]:
# convert string datatype
df["ISBN-13"] = df["ISBN-13"].astype("string")

In [62]:
# remove extra spaces
df["ISBN-13"] = df["ISBN-13"].astype("string").str.strip()

In [63]:
df["ISBN-13"].dtype

string[python]

In [64]:
df["ISBN-13"].str.len().value_counts()

ISBN-13
13    10320
12       14
11       10
10        1
Name: count, dtype: Int64

In [65]:
df = df[df["ISBN-13"].notna()].copy()

df["ISBN-13"] = df["ISBN-13"].astype("string").str.strip()

df = df[df["ISBN-13"].str.len() == 13].copy()

In [66]:
df["ISBN-13"].str.len().value_counts()

ISBN-13
13    10320
Name: count, dtype: Int64

In [67]:
df.head()

,Book_ID,Book_Title,Authors,Rating,ISBN-10,ISBN-13,Language_Code,Num_Of_Pages,Ratings_Count,Number_of_reviews,publication_date,Publisher,Publication_year
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,2006-09-16,Scholastic Inc.,2006
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,2004-09-01,Scholastic Inc.,2004
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,2003-11-01,Scholastic,2003
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,2004-05-01,Scholastic Inc.,2004
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,2004-09-13,Scholastic,2004

In [68]:
df.columns

Index(['Book_ID', 'Book_Title', 'Authors', 'Rating', 'ISBN-10', 'ISBN-13',
       'Language_Code', 'Num_Of_Pages', 'Ratings_Count', 'Number_of_reviews',
       'publication_date', 'Publisher', 'Publication_year'],
      dtype='object')

In [69]:
# arrange the columns in a logical order
df = df[
    [
        "Book_ID",
        "Book_Title",
        "Authors",
        "Rating",
        "Number_of_reviews",
        "Ratings_Count",
        "ISBN-10",
        "ISBN-13",
        "Num_Of_Pages",
        "Language_Code",
        "publication_date",
        "Publication_year",
        "Publisher"\
    ]
]

In [70]:
df.head()

,Book_ID,Book_Title,Authors,Rating,Number_of_reviews,Ratings_Count,ISBN-10,ISBN-13,Num_Of_Pages,Language_Code,publication_date,Publication_year,Publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,27591,2095690,0439785960,9780439785969,652,eng,2006-09-16,2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,29221,2153167,0439358078,9780439358071,870,eng,2004-09-01,2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,244,6333,0439554896,9780439554893,352,eng,2003-11-01,2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,36325,2339585,043965548X,9780439655484,435,eng,2004-05-01,2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,164,41428,0439682584,9780439682589,2690,eng,2004-09-13,2004,Scholastic

In [71]:
df = df.drop("publication_date",axis =1)

In [72]:
df.head()

,Book_ID,Book_Title,Authors,Rating,Number_of_reviews,Ratings_Count,ISBN-10,ISBN-13,Num_Of_Pages,Language_Code,Publication_year,Publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,27591,2095690,0439785960,9780439785969,652,eng,2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,29221,2153167,0439358078,9780439358071,870,eng,2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,244,6333,0439554896,9780439554893,352,eng,2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,36325,2339585,043965548X,9780439655484,435,eng,2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,164,41428,0439682584,9780439682589,2690,eng,2004,Scholastic

In [73]:
df = df.reset_index(drop=True)

In [74]:
df

,Book_ID,Book_Title,Authors,Rating,Number_of_reviews,Ratings_Count,ISBN-10,ISBN-13,Num_Of_Pages,Language_Code,Publication_year,Publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,27591,2095690,0439785960,9780439785969,652,eng,2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,29221,2153167,0439358078,9780439358071,870,eng,2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,244,6333,0439554896,9780439554893,352,eng,2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,36325,2339585,043965548X,9780439655484,435,eng,2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,164,41428,0439682584,9780439682589,2690,eng,2004,Scholastic
...,...,...,...,...,...,...,...,...,...,...,...,...
10315,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,20,156,1560254416,9781560254416,512,eng,2004,Da Capo Press
10316,45633,You Bright and Risen Angels,William T. Vollmann,4.08,56,783,0140110879,9780140110876,635,eng,1988,Penguin Books
10317,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,95,820,0140131965,9780140131963,415,eng,1993,Penguin Books
10318,45639,Poor People,William T. Vollmann,3.72,139,769,0060878827,9780060878825,434,eng,2007,Ecco
10319,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,12,113,8497646983,9788497646987,272,spa,2006,Edimat Libros

In [75]:
df.columns

Index(['Book_ID', 'Book_Title', 'Authors', 'Rating', 'Number_of_reviews',
       'Ratings_Count', 'ISBN-10', 'ISBN-13', 'Num_Of_Pages', 'Language_Code',
       'Publication_year', 'Publisher'],
      dtype='object')

# ISBN-13

In [76]:
df["ISBN-13"] = df["ISBN-13"].astype(str)

In [77]:
# clean spaces in text columns
text_cols = [
    "Book_Title",
    "Authors",
    "ISBN-10",
    "ISBN-13",
    "Language_Code",
    "Publisher"
]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

In [78]:
# check the duplicate books

df["Book_Title"].duplicated().sum()

np.int64(0)

In [79]:
df["ISBN-13"].duplicated().sum()

np.int64(0)

# check Rating

In [80]:
# shows normaly be in between 0 to 5
df["Rating"].min(),df["Rating"].max()

(0.0, 5.0)

In [81]:
# check unusual values
df[(df["Rating"] < 0) | (df["Rating"] > 5)]

Empty DataFrame
Columns: [Book_ID, Book_Title, Authors, Rating, Number_of_reviews, Ratings_Count, ISBN-10, ISBN-13, Num_Of_Pages, Language_Code, Publication_year, Publisher]
Index: []

# check Publication_year

In [82]:
df["Publication_year"].min(), df["Publication_year"].max()

(np.int64(1900), np.int64(2020))

In [83]:
df["Publication_year"].value_counts().sort_index()

Publication_year
1900    1
1913    1
1914    1
1919    1
1921    2
       ..
2016    6
2017    7
2018    5
2019    6
2020    1
Name: count, Length: 86, dtype: Int64

# check number of pages

In [84]:
df[df["Num_Of_Pages"] <= 0]

,Book_ID,Book_Title,Authors,Rating,Number_of_reviews,Ratings_Count,ISBN-10,ISBN-13,Num_Of_Pages,Language_Code,Publication_year,Publisher
282,955,The 5 Love Languages / The 5 Love Languages Jo...,Gary Chapman,4.70,4,22,0802415318,9780802415318,0,eng,2005,Moody Publishers
775,2835,The Tragedy of Pudd'nhead Wilson,Mark Twain/Michael Prichard,3.79,0,3,140015068X,9781400150687,0,eng,2003,Tantor Media
970,3593,Murder by Moonlight & Other Mysteries (New Adv...,NOT A BOOK,4.00,2,7,0743564677,9780743564670,0,eng,2006,Simon Schuster Audio
973,3599,The Unfortunate Tobacconist & Other Mysteries ...,NOT A BOOK,3.50,1,12,074353395X,9780743533959,0,eng,2003,Simon & Schuster Audio
1430,5362,The Summons / The Brethren,John Grisham/Michael Beck/Frank Muller,3.99,9,241,0739342770,9780739342770,0,eng,2006,Random House Audio
...,...,...,...,...,...,...,...,...,...,...,...,...
9292,40378,The Chessmen of Mars (Barsoom #5),Edgar Rice Burroughs/John Bolen,3.83,157,5147,1400130212,9781400130214,0,eng,2005,Tantor Media
9450,41273,Fine Lines (One-Eyed Mack #6),Jim Lehrer,3.23,4,17,0517164353,9780517164358,0,eng,1995,Random House Value Publishing
9855,43343,Stowaway and Milk Run: Two Unabridged Stories ...,Mary Higgins Clark/Jan Maxwell,3.49,2,64,0671046241,9780671046248,0,eng,1999,Simon & Schuster Audio
10145,44748,The Mask of the Enchantress,Victoria Holt,3.85,1,21,0449210847,9780449210840,0,eng,1981,Ivy Books
10278,45472,Treasury of American Tall Tales: Volume 1: Dav...,David Bromberg/Jay Ungar/Molly Mason/Garrison ...,3.86,9,36,0739336509,9780739336502,0,eng,2006,Listening Library (Audio)

In [85]:
df["Num_Of_Pages"].value_counts().loc[0]

np.int64(65)

In [86]:
import numpy as np

df["Num_Of_Pages"] = df["Num_Of_Pages"].replace(0, np.nan)

In [87]:
df["Num_Of_Pages"].isna().sum()

np.int64(65)

In [88]:
df=df.dropna(subset=["Num_Of_Pages"])

In [89]:
df["Num_Of_Pages"].isna().sum()

np.int64(0)

# check Number_of_reviews

In [90]:
df[df["Number_of_reviews"]<0]

Empty DataFrame
Columns: [Book_ID, Book_Title, Authors, Rating, Number_of_reviews, Ratings_Count, ISBN-10, ISBN-13, Num_Of_Pages, Language_Code, Publication_year, Publisher]
Index: []

In [91]:
df["Number_of_reviews"].describe()

count    10255.000000
mean       533.361775
std       2511.292343
min          0.000000
25%          9.000000
50%         49.000000
75%        248.000000
max      94265.000000
Name: Number_of_reviews, dtype: float64

In [92]:
df["Number_of_reviews"].value_counts().loc[0]

np.int64(577)

In [93]:
df["Number_of_reviews"] = df["Number_of_reviews"].replace(0, np.nan)

C:\Users\deore\AppData\Local\Temp\ipykernel_11960\2630976911.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Number_of_reviews"] = df["Number_of_reviews"].replace(0, np.nan)

In [94]:
df["Number_of_reviews"].isna().sum()

np.int64(577)

In [95]:
df=df.dropna(subset=["Number_of_reviews"])

In [96]:



df['Number_of_reviews'].isna().sum()

np.int64(0)

# check Ratings_count

In [97]:
df["Ratings_Count"].value_counts().loc[0]

np.int64(2)

In [98]:
df["Ratings_Count"] = df["Ratings_Count"].replace(0, np.nan)

In [99]:
df["Ratings_Count"].isna().sum()

np.int64(2)

In [100]:
df=df.dropna(subset=["Ratings_Count"])

In [101]:
df["Ratings_Count"].isna().sum()

np.int64(0)

# stadardize Language_code

In [102]:
df["Language_Code"].value_counts()

Language_Code
eng      7823
en-US    1264
en-GB     178
spa       164
fre        96
ger        55
jpn        32
mul        17
por        10
grc         7
en-CA       7
ita         5
enm         3
zho         3
lat         3
rus         2
glg         1
swe         1
nor         1
ara         1
msa         1
nl          1
tur         1
Name: count, dtype: int64

In [103]:
df["Language_Code"].isna().sum()

np.int64(0)

In [104]:
df = df.copy()

In [105]:
# standardize Authors

In [106]:
df["Authors"] = df["Authors"].str.strip()

# standardize Publisher

In [107]:
print(df["Publisher"].value_counts())

Publisher
Vintage                                    297
Penguin Books                              225
Penguin Classics                           146
Mariner Books                              143
Ballantine Books                           137
                                          ...
Tyndale Momentum                             1
Houghton Mifflin Co. (Boston/NY)             1
Inkling Books                                1
AVA Publishing                               1
Dodd Mead; 1st edition (September 1976)      1
Name: count, Length: 2002, dtype: int64

In [108]:
print(df["Publisher"].value_counts().to_string())

Publisher
Vintage                                                                297
Penguin Books                                                          225
Penguin Classics                                                       146
Mariner Books                                                          143
Ballantine Books                                                       137
Bantam                                                                 105
Harper Perennial                                                       104
HarperCollins                                                          102
Pocket Books                                                           100
VIZ Media LLC                                                           88
Berkley                                                                 84
Del Rey                                                                 76
Tor Books                                                               73
Dover Publications                                                      70
Scribner                                                                69
Grand Central Publishing                                                67
Modern Library                                                          66
W. W. Norton  Company                                                   66
Oxford University Press  USA                                            61
Anchor                                                                  60
Signet                                                                  56
William Morrow Paperbacks                                               56
Simon  Schuster                                                         56
Oxford University Press                                                 55
Avon                                                                    55
Scholastic Paperbacks                                                   54
Library of America                                                      52
Penguin                                                                 50
Cambridge University Press                                              50
Puffin Books                                                            48
HarperTorch                                                             46
Broadway Books                                                          46
Harry N. Abrams                                                         43
St. Martin's Press                                                      43
Berkley Books                                                           42
St. Martin's Griffin                                                    42
Vertigo                                                                 42
HarperCollins Publishers                                                41
Simon & Schuster                                                        41
University of Chicago Press                                             41
Bantam Books                                                            40
G.P. Putnam's Sons                                                      39
Basic Books                                                             38
Anchor Books                                                            38
Picador                                                                 38
DAW                                                                     38
Back Bay Books                                                          37
Grove Press                                                             37
Farrar  Straus and Giroux                                               36
Harper                                                                  36
St. Martin's Paperbacks                                                 36
Houghton Mifflin Harcourt                                               36
Harvard University Press                                                35
Washington Square Press                                                 35
HarperOne                                                               35
Ace                                                                     34
Plume                                                                   34
Random House Books for Young Readers                                    34
DC Comics                                                               31
Princeton University Press                                              31
Del Rey Books                                                           31
HMH Books for Young Readers                                             31
W. W. Norton & Company                                                  30
Delta                                                                   30
Yearling                                                                28
Scholastic                                                              28
William Morrow                                                          28
Alfred A. Knopf                                                         28
Free Press                                                              27
Everyman's Library                                                      27
Cliffs Notes                                                            27
Arrow                                                                   27
Random House                                                            27
Wizards of the Coast                                                    26
Picador USA                                                             26
Ace Books                                                               24
Harper Perennial Modern Classics                                        24
Routledge                                                               24
Dell                                                                    24
Riverhead Books                                                         24
Random House Trade Paperbacks                                           23
University of California Press                                          23
Warner Books                                                            22
Penguin Books Ltd                                                       22
Yale University Press                                                   22
Leisure Books                                                           22
Warner Books (NY)                                                       21
Tyndale House Publishers                                                21
Hackett Publishing Company  Inc.                                        21
Marvel                                                                  21
Atria Books                                                             21
Spectra                                                                 21
Da Capo Press                                                           21
Little  Brown and Company                                               20
Puffin                                                                  20
Harper Voyager                                                          20
Touchstone                                                              20
Little  Brown Books for Young Readers                                   20
Hachette Books                                                          20
Candlewick Press                                                        20
Bloomsbury Academic                                                     19
NAL                                                                     19
Fawcett                                                                 19
Ecco                                                                    19
Avon Books                                                              19
Jove                                                                    19
HarperTrophy                                                            19
Viz Media                                                               19
Thomas Nelson                                                           19
TokyoPop                                                                19
Corgi                                                                   18
Wiley                                                                   18
New Directions                                                          18
Delacorte Press                                                         17
Tor Fantasy                                                             17
Orb Books                                                               17
Greenwillow Books                                                       16
Doubleday Books                                                         16
Firebird                                                                16
Vintage Classics                                                        16
Aladdin                                                                 16
Barnes  Noble Classics                                                  16
Dark Horse Books                                                        16
Vintage International                                                   16
Prentice Hall                                                           16
Signet Classics                                                         16
Houghton Mifflin                                                        15
Orion                                                                   15
Vintage Crime/Black Lizard                                              15
Simon Pulse                                                             15
Gallery Books                                                           15
Baen                                                                    14
Pocket                                                                  14
Gallimard                                                               14
Pantheon                                                                14
Faber & Faber                                                           14
Kensington                                                              14
Knopf Publishing Group                                                  14
Disney Press                                                            14
Berkley Sensation                                                       14
NYRB Classics                                                           14
Random House Trade                                                      14
Daw Books                                                               13
Random House Value Publishing                                           13
Dial Press                                                              13
VIZ Media                                                               13
Zondervan                                                               13
W.W. Norton & Company                                                   13
Vision                                                                  13
Bloomsbury Publishing PLC                                               13
Dell Publishing Company                                                 13
Chronicle Books                                                         13
Little Brown and Company                                                13
Andrews McMeel Publishing                                               13
Plume Books                                                             13
Verso                                                                   13
Brilliance Audio                                                        13
Viking Books                                                            12
Pantheon Books                                                          12
Open Court                                                              12
Citadel                                                                 12
Columbia University Press                                               12
Dial Press Trade Paperback                                              12
McSweeney's                                                             12
集英社                                                                     12
Turtleback Books                                                        12
Little  Brown Book Group                                                12
Pocket Star                                                             12
Headline                                                                12
University Press of Mississippi                                         11
Schocken                                                                11
Gramercy Books                                                          11
Berkley Trade                                                           11
Mira Books                                                              11
Knopf                                                                   11
Faber and Faber                                                         11
Harmony                                                                 11
Harvest House Publishers                                                11
Running Press                                                           11
Spectra Books                                                           11
Black Swan                                                              11
Scholastic Inc.                                                         11
Fawcett Books                                                           11
Headline Review                                                         10
Farrar Straus Giroux                                                    10
Crossway Books                                                          10
Three Rivers Press                                                      10
The New Press                                                           10
Harcourt                                                                10
O'Reilly Media                                                          10
Plaza y Janes                                                           10
Luna Books                                                              10
Wings                                                                   10
Viking                                                                  10
Pearson                                                                 10
Zebra                                                                   10
Planeta Publishing                                                      10
Vintage Books                                                           10
HarperTeen                                                              10
Bethany House Publishers                                                10
Dark Horse Manga                                                        10
Shambhala                                                               10
Disney-Hyperion                                                          9
Grosset & Dunlap                                                         9
Onyx                                                                     9
Digital Manga Publishing                                                 9
MIRA                                                                     9
Wordsworth Editions                                                      9
St. Martins Press-3PL                                                    9
Random House Audio                                                       9
Black Dog & Leventhal Publishers                                         9
Aladdin Paperbacks                                                       9
Love Spell                                                               9
DK Children                                                              9
Chaosium                                                                 9
Faber  Faber                                                             9
Laurel Leaf Library                                                      9
Harper Business                                                          9
Doubleday                                                                9
Beacon Press                                                             9
Minotaur Books                                                           9
Bloomsbury                                                               9
Severn House Publishers                                                  9
Yearling Books                                                           9
ADV Manga                                                                9
Vintage Books USA                                                        9
Ediciones B                                                              9
Time Life Medical                                                        8
It Books                                                                 8
Scholastic  Inc.                                                         8
MIT Press                                                                8
Ignatius Press                                                           8
Univ Of Minnesota Press                                                  8
Roc                                                                      8
Bantam Classics                                                          8
Dalkey Archive Press                                                     8
Bantam Spectra                                                           8
小学館                                                                      8
For Dummies                                                              8
Punto de Lectura                                                         8
Signet Book                                                              8
Amistad                                                                  8
Orbit                                                                    8
J'ai Lu                                                                  8
Debolsillo                                                               8
Clarion Books                                                            8
Laurel Leaf                                                              8
University of Oklahoma Press                                             8
Little  Brown & Company                                                  8
Villard                                                                  8
Pinnacle                                                                 7
Clarkson Potter                                                          7
Harlequin                                                                7
University Of Chicago Press                                              7
Houghton Mifflin Company                                                 7
Harper Paperbacks                                                        7
Jossey-Bass                                                              7
Crown                                                                    7
Baen Books                                                               7
Scribner Book Company                                                    7
Le Livre de Poche                                                        7
Tarcherperigee                                                           7
AudioGO                                                                  7
Simon  Schuster Books for Young Readers                                  7
Blackstone Audiobooks                                                    7
Blu                                                                      7

In [109]:
df[df["Publisher"].str.contains("Scholastic", case=False, na=False)]["Publisher"].value_counts()

Publisher
Scholastic Paperbacks            54
Scholastic                       28
Scholastic Inc.                  11
Scholastic  Inc.                  8
Scholastic Press                  7
Scholastic Books                  3
Apple Paperbacks (Scholastic)     1
Scholastic Inc                    1
Hippo/Scholastic                  1
Chicken House / Scholastic        1
Scholastic Audio Books            1
Scholastic Nonfiction             1
Name: count, dtype: int64

In [110]:
df["Publisher"] = df["Publisher"].replace({
    "Scholastic  Inc.": "Scholastic Inc.",
    "Scholastic Inc": "Scholastic Inc."
})

In [111]:
df[df["Publisher"].str.contains("Scholastic", case=False, na=False)]["Publisher"].value_counts()

Publisher
Scholastic Paperbacks            54
Scholastic                       28
Scholastic Inc.                  20
Scholastic Press                  7
Scholastic Books                  3
Apple Paperbacks (Scholastic)     1
Hippo/Scholastic                  1
Chicken House / Scholastic        1
Scholastic Audio Books            1
Scholastic Nonfiction             1
Name: count, dtype: int64

In [112]:

import pandas as pd

pd.set_option("display.max_rows", None
             

print(df["Publisher"].value_counts(dropna=False))

SyntaxError: '(' was never closed (765430011.py, line 3)

In [ ]:
df["Publisher"] = df["Publisher"].str.replace(r"\s+", " ", regex=True).str.strip()

In [ ]:
# Standardize whitespace
df["Publisher"] = (
    df["Publisher"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

# Fix obvious exact duplicates
df["Publisher"] = df["Publisher"].replace({
    "Scholastic Inc": "Scholastic Inc.",
})

In [ ]:


import pandas as pd

pd.set_option("display.max_rows", None)
             

print(df["Publisher"].value_counts(dropna=False))

In [ ]:
df["Publisher"] = (
    df["Publisher"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [ ]:
publisher_map = {
    "Scholastic Inc": "Scholastic Inc.",
    "W.W. Norton & Company": "W. W. Norton & Company",
    "W.W. Norton": "W. W. Norton",
    "Simon Schuster": "Simon & Schuster",
    "Simon and Schuster": "Simon & Schuster",
    "Little Brown and Company": "Little Brown & Company",
    "Farrar Straus and Giroux": "Farrar, Straus and Giroux",
    "Farrar Straus Giroux": "Farrar, Straus and Giroux",
    "Farrar Straus & Giroux": "Farrar, Straus and Giroux",
    "Faber and Faber": "Faber & Faber",
    "Faber Faber": "Faber & Faber",
    "Harpercollins": "HarperCollins",
    "Harper Collins": "HarperCollins",
    "Harpperen": "Harperen",
    "Bantem Press": "Bantam Press",
    "Fawcett crest": "Fawcett Crest",
    "Readers Digest.": "Readers Digest",
    "Hamish hamilton": "Hamish Hamilton",
    "TusQuets": "Tusquets",
    "Tokyopop": "TokyoPop",
    "J'ai lu": "J'ai Lu",
    "University Of Chicago Press": "University of Chicago Press",
    "Thames Hudson": "Thames & Hudson",
    "Thames & Hudson": "Thames & Hudson",
}

In [ ]:
df["Publisher"] = df["Publisher"].replace(publisher_map)

In [ ]:
import numpy as np

df["Publisher"] = df["Publisher"].replace(
    ["Not Avail", "N/A", "NA", "Not Available", ""],
    np.nan
)

In [ ]:
print(df["Publisher"].value_counts(dropna=False).to_string())

In [ ]:
df["Publisher"].isna().sum()

In [ ]:
df = df.dropna(subset=["Publisher"])

In [ ]:
print(df["Publisher"].value_counts(dropna=False).to_string())

In [ ]:
# 1. Remove extra spaces
df["Publisher"] = (
    df["Publisher"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [ ]:
publisher_map = {
    "Scholastic Inc": "Scholastic Inc.",
    "W.W. Norton & Company": "W. W. Norton & Company",
    "W.W. Norton & Company (NY)": "W. W. Norton & Company",
    "W.W. Norton & Company (NYC)": "W. W. Norton & Company",
    "Bantem Press": "Bantam Press",
    "Random house": "Random House",
    "Harpercollins": "HarperCollins",
    "Harpercollins Childrens Books": "HarperCollins Children's Books",
    "TusQuets": "Tusquets",
    "Farrar Straus and Giroux": "Farrar, Straus and Giroux",
    "Farrar Straus and Giroux (NY)": "Farrar, Straus and Giroux",
    "Chatto Windus": "Chatto & Windus",
    "Chatto and Windus": "Chatto & Windus",
    "Inter Varsity Press": "InterVarsity Press",
    "Inter-Varsity Press": "InterVarsity Press",
}

In [ ]:
df["Publisher"] = df["Publisher"].replace(publisher_map)

In [ ]:
print(df["Publisher"].value_counts().to_string())

In [ ]:
# 1. Remove extra spaces
df["Publisher"] = (
    df["Publisher"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

# 2. Fix clear spelling / formatting inconsistencies
publisher_map = {
    # W. W. Norton
    "W.W. Norton Company": "W. W. Norton Company",
    "W.W. Norton & Company": "W. W. Norton & Company",
    "W.W. Norton": "W. W. Norton",

    # Simon & Schuster
    "Simon Schuster": "Simon & Schuster",

    # Little Brown
    "Little Brown and Company": "Little Brown & Company",

    # Farrar
    "Farrar Straus and Giroux": "Farrar, Straus and Giroux",

    # Faber
    "Faber and Faber": "Faber & Faber",
    "Faber Faber": "Faber & Faber",

    # HarperCollins
    "Harpercollins": "HarperCollins",
    "Harper Collins": "HarperCollins",
    "Harpercollins Children's Books": "HarperCollins Children's Books",
    "HarperCollinsPublishers": "HarperCollins Publishers",

    # Scholastic
    "Scholastic Inc": "Scholastic Inc.",

    # Bantam
    "Bantem Press": "Bantam Press",

    # Other clear typos / formatting
    "TusQuets": "Tusquets",
    "Chatto Windus": "Chatto & Windus",
    "Chatto and Windus": "Chatto & Windus",
    "Inter Varsity Press": "InterVarsity Press",
    "Inter-Varsity Press": "InterVarsity Press",
    "Random house": "Random House",
    "Hamish hamilton": "Hamish Hamilton",
    "Readers Digest.": "Readers Digest",
    "Fawcett crest": "Fawcett Crest",
    "Harper Teen": "HarperTeen",
    "Tarcherperigee": "TarcherPerigee",
    "HarperPaperbacks": "Harper Paperbacks",
    "Hartorch": "HarperTorch",
    "B Books": "B Books",
    "Millenium": "Millennium",
    "Elloras Cave": "Ellora's Cave",
    "Serpents Tail": "Serpent's Tail",
    "Gingko Press": "Ginkgo Press",
    "Ballantine Books": "Ballantine Books",
}

df["Publisher"] = df["Publisher"].replace(publisher_map)

In [ ]:
print(df["Publisher"].value_counts(dropna=False).to_string())

In [ ]:
print("Unique publishers:", df["Publisher"].nunique())

In [ ]:
df.info()

In [ ]:
df.to_csv("clean_books2.csv", index=False)