In [55]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
# Load dataset

df = pd.read_csv(
    r"C:\Users\deore\Downloads\archive (2)\books.csv",
    on_bad_lines="skip"
)

In [57]:
# inspect the dataset

df.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [58]:
type(df)

pandas.core.frame.DataFrame

In [59]:
df.shape

(11123, 12)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11123 entries, 0 to 11122
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              11123 non-null  int64
 1   title               11123 non-null  object
 2   authors             11123 non-null  object
 3   average_rating      11123 non-null  float64
 4   isbn                11123 non-null  object
 5   isbn13              11123 non-null  int64
 6   language_code       11123 non-null  object
 7     num_pages         11123 non-null  int64
 8   ratings_count       11123 non-null  int64
 9   text_reviews_count  11123 non-null  int64
 10  publication_date    11123 non-null  object
 11  publisher           11123 non-null  object
dtypes: float64(1), int64(5), object(6)
memory usage: 1.0+ MB

In [61]:
df.describe()

,bookID,average_rating,isbn13,num_pages,ratings_count,text_reviews_count
count,11123.000000,11123.000000,1.112300e+04,11123.000000,1.112300e+04,11123.000000
mean,21310.856963,3.934075,9.759880e+12,336.405556,1.794285e+04,542.048099
std,13094.727252,0.350485,4.429758e+11,241.152626,1.124992e+05,2576.619589
min,1.000000,0.000000,8.987060e+09,0.000000,0.000000e+00,0.000000
25%,10277.500000,3.770000,9.780345e+12,192.000000,1.040000e+02,9.000000
50%,20287.000000,3.960000,9.780582e+12,299.000000,7.450000e+02,47.000000
75%,32104.500000,4.140000,9.780872e+12,416.000000,5.000500e+03,238.000000
max,45641.000000,5.000000,9.790008e+12,6576.000000,4.597666e+06,94265.000000

In [62]:
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', '  num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='object')

In [63]:
# clean column names 

df.columns = df.columns.str.strip()
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', 'num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='object')

In [64]:
# check missing values

df.isnull().sum()

bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
num_pages             0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

In [65]:
# check missing values percentage in each column
(df.isnull().sum() / len(df) * 100).round(2)

bookID                0.0
title                 0.0
authors               0.0
average_rating        0.0
isbn                  0.0
isbn13                0.0
language_code         0.0
num_pages             0.0
ratings_count         0.0
text_reviews_count    0.0
publication_date      0.0
publisher             0.0
dtype: float64

In [66]:
df = df.copy()

# remove duplicate records

In [67]:
# count duplicates
df.duplicated().sum()

np.int64(0)

# title column

In [68]:
# count duplicate title in dataset
df["title"].duplicated().sum()

np.int64(775)

In [69]:
# print rows of duplicate title
df.loc[df["title"].duplicated(), "title"]

10       The Hitchhiker's Guide to the Galaxy (Hitchhik...
24       The Lord of the Rings (The Lord of the Rings  ...
37                                          The Changeling
40                                         The Known World
41                                         The Known World
                               ...
11075            Encuentro en el Ártico (Artemis Fowl  #2)
11076                      Artemis Fowl (Artemis Fowl  #1)
11078            The Subtle Knife (His Dark Materials  #2)
11080            The Subtle Knife (His Dark Materials  #2)
11096                                          On the Road
Name: title, Length: 775, dtype: object

In [70]:
#  see all duplicate titles
df[df["title"].duplicated(keep=False)]

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
9,14,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams,4.22,1400052920,9781400052929,eng,215,4930,460,8/3/2004,Crown
10,16,The Hitchhiker's Guide to the Galaxy (Hitchhik...,Douglas Adams/Stephen Fry,4.22,0739322206,9780739322208,eng,6,1266,253,3/23/2005,Random House Audio
...,...,...,...,...,...,...,...,...,...,...,...,...
11075,45463,Encuentro en el Ártico (Artemis Fowl #2),Eoin Colfer/Ana Alcaina Pérez,3.95,0307343103,9780307343109,spa,320,15,3,7/5/2005,Montena
11076,45465,Artemis Fowl (Artemis Fowl #1),Eoin Colfer/Nathaniel Parker,3.84,1400085918,9781400085910,eng,6,55,14,4/6/2004,Listening Library
11078,45479,The Subtle Knife (His Dark Materials #2),Philip Pullman/Ian Beck,4.13,0375846727,9780375846724,eng,326,677,77,9/1/2007,Alfred A. Knopf Books for Young Readers
11080,45485,The Subtle Knife (His Dark Materials #2),Philip Pullman,4.13,0807210471,9780807210475,eng,8,39,8,1/28/2000,Listening Library
11096,45536,On the Road,Jack Kerouac/Ann Charters,3.63,0142437255,9780142437254,en-US,307,3271,342,1/3/2006,Penguin Classics

In [71]:
# remove duplicate rows and keep first
df = df.drop_duplicates("title",keep="first")

In [72]:
# check duplicates
df["title"].duplicated().sum()

np.int64(0)

In [73]:
# find the type of the title colum
df["title"].dtypes

dtype('O')

In [74]:
df = df.copy()

# authors column

In [75]:
# find type of author
df['authors'].dtypes

dtype('O')

In [76]:

df['authors'].isna().sum()

np.int64(0)

# rating column

In [77]:
# find type of rating 
df["average_rating"].dtypes

dtype('float64')

In [78]:
# check null values
df["average_rating"].isna().sum()

np.int64(0)

In [79]:
# check invalid ratings
i=df[
    (df["average_rating"] < 0) |
    (df["average_rating"] > 5)
]

i

Empty DataFrame
Columns: [bookID, title, authors, average_rating, isbn, isbn13, language_code, num_pages, ratings_count, text_reviews_count, publication_date, publisher]
Index: []

In [80]:
# find the min and max of the average_rating column
df["average_rating"].min(), df["average_rating"].max()

(0.0, 5.0)

In [81]:
df = df.copy()

# Publication date

In [82]:
# check the type of publication_date
df["publication_date"].dtypes

dtype('O')

In [83]:
# find the missing values
df["publication_date"].isna().sum()

np.int64(0)

In [84]:
df = df.copy()

In [85]:
# convert object to datetime format
df["publication_date"] = pd.to_datetime(
    df["publication_date"],
    errors = "coerce")

In [86]:
# create a separate year column
df["publication_year"] = df["publication_date"].dt.year

In [87]:
# check both columns
df[["publication_date","publication_year"]].head()

  publication_date  publication_year
0       2006-09-16            2006.0
1       2004-09-01            2004.0
2       2003-11-01            2003.0
3       2004-05-01            2004.0
4       2004-09-13            2004.0

In [88]:
# check type of publication_year
df["publication_year"].dtypes

dtype('float64')

In [89]:
# convert float to int
df["publication_year"]=df["publication_year"].astype("Int64")

In [90]:
# check the type
df["publication_year"].dtypes

Int64Dtype()

In [91]:
df["publication_year"].isnull().sum()

np.int64(2)

In [92]:
df = df.dropna(subset=["publication_year"])

In [93]:
df["publication_year"].dtypes

Int64Dtype()

In [94]:
df["publication_year"].isnull().sum()

np.int64(0)

In [95]:
df.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', 'num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher', 'publication_year'],
      dtype='object')

In [96]:
df =df.copy()

# author coloum

In [97]:
# find the type of author
df["authors"].dtypes

dtype('O')

In [98]:
# convert all values of authors coloumn into string type
df["authors"] = ( 
    df["authors"]
    .astype("string")
    .str.strip()
)

In [99]:
df["authors"].dtypes

string[python]

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10346 entries, 0 to 11122
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   bookID              10346 non-null  int64
 1   title               10346 non-null  object
 2   authors             10346 non-null  string
 3   average_rating      10346 non-null  float64
 4   isbn                10346 non-null  object
 5   isbn13              10346 non-null  int64
 6   language_code       10346 non-null  object
 7   num_pages           10346 non-null  int64
 8   ratings_count       10346 non-null  int64
 9   text_reviews_count  10346 non-null  int64
 10  publication_date    10346 non-null  datetime64[ns]
 11  publisher           10346 non-null  object
 12  publication_year    10346 non-null  Int64
dtypes: Int64(1), datetime64[ns](1), float64(1), int64(5), object(4), string(1)
memory usage: 1.1+ MB

In [101]:
df["authors"].value_counts()

authors
Rumiko Takahashi                                          39
P.G. Wodehouse                                            39
Orson Scott Card                                          33
Piers Anthony                                             30
Agatha Christie                                           30
                                                          ..
Hugh    Miller                                             1
Lonely Planet/Sarah Johnstone/Steve Fallon                 1
David Salo                                                 1
Rough Guides/Jan Dodd/Mark Lewis/Ron Emmons                1
William T. Vollmann/Larry McCaffery/Michael Hemmingson     1
Name: count, Length: 6295, dtype: Int64

# text_reviews_count  column

In [102]:
df["text_reviews_count"].dtypes

dtype('int64')

In [103]:
df["text_reviews_count"].isna().sum()

np.int64(0)

In [104]:
df["text_reviews_count"].head()

0    27591
1    29221
2      244
3    36325
4      164
Name: text_reviews_count, dtype: int64

In [105]:
df = df.copy()

# rename colums and drop columns

In [112]:
df.columns

Index(['Book_ID', 'Book_Title', 'Authors', 'Rating', 'ISBN-10', 'ISBN-13',
       'Language_Code', 'Num_Of_Pages', 'Ratings_Count', 'Number_of_reviews',
       'publication_date', 'Publisher', 'Publication_year'],
      dtype='object')

In [111]:
df.rename(columns={"bookID":"Book_ID",
          "title":"Book_Title",
          "authors":"Authors",
          "average_rating":"Rating",
          "isbn":"ISBN-10",
          "isbn13":"ISBN-13",
          "num_pages":"Num_Of_Pages",
          "text_reviews_count":"Number_of_reviews",
          "publication_year":"Publication_year",
          "publisher":"Publisher",
          "language_code":"Language_Code",
          "ratings_count":"Ratings_Count",
                   
           
        
          },inplace = True)

In [108]:
• Book title
• Author
• Genre
• Rating
• Number of reviews
• Publication year
• Price
• Publisher

SyntaxError: invalid character '•' (U+2022) (3819630919.py, line 1)

In [ ]:
df=df.columns.str.strip()

In [ ]:
df = df.copy()

In [ ]:
type(df)

In [ ]:
df.head()

In [ ]:
df["Rating"].max()

In [ ]:
df["Rating"].min()

# ISBN -10 column

In [ ]:
df["ISBN-10"].duplicated().sum()

In [ ]:

df["ISBN-10"].str.len().value_counts()

In [ ]:
df = df[df["ISBN-10"].notna()].copy()

df["ISBN-10"] = df["ISBN-10"].astype("string").str.strip()

df = df[df["ISBN-10"].str.len() == 10].copy()

In [ ]:

df["ISBN-10"].str.len().value_counts()

# ISBN-13 colum

In [ ]:
df["ISBN-10"].dtypes

In [ ]:
# convert string datatype
df["ISBN-13"] = df["ISBN-13"].astype("string")

In [ ]:
# remove extra spaces
df["ISBN-13"] = df["ISBN-13"].astype("string").str.strip()

In [ ]:
df["ISBN-13"].dtype

In [ ]:
df["ISBN-13"].str.len().value_counts()

In [ ]:
df = df[df["ISBN-13"].notna()].copy()

df["ISBN-13"] = df["ISBN-13"].astype("string").str.strip()

df = df[df["ISBN-13"].str.len() == 13].copy()

In [ ]:
df["ISBN-13"].str.len().value_counts()

In [ ]:
df.head()

In [ ]:
df.columns

In [114]:
# arrange the columns in a logical order
df = df[
    [
        "Book_ID",
        "Book_Title",
        "Authors",
        "Rating",
        "Number_of_reviews",
        "Ratings_Count",
        "ISBN-10",
        "ISBN-13",
        "Num_Of_Pages",
        "Language_Code",
        "publication_date",
        "Publication_year",
        "Publisher"\
    ]
]

In [115]:
df.head()

,Book_ID,Book_Title,Authors,Rating,Number_of_reviews,Ratings_Count,ISBN-10,ISBN-13,Num_Of_Pages,Language_Code,publication_date,Publication_year,Publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,27591,2095690,0439785960,9780439785969,652,eng,2006-09-16,2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,29221,2153167,0439358078,9780439358071,870,eng,2004-09-01,2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,244,6333,0439554896,9780439554893,352,eng,2003-11-01,2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,36325,2339585,043965548X,9780439655484,435,eng,2004-05-01,2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,164,41428,0439682584,9780439682589,2690,eng,2004-09-13,2004,Scholastic

In [116]:
df = df.drop("publication_date",axis =1)

In [117]:
df.head()

,Book_ID,Book_Title,Authors,Rating,Number_of_reviews,Ratings_Count,ISBN-10,ISBN-13,Num_Of_Pages,Language_Code,Publication_year,Publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,27591,2095690,0439785960,9780439785969,652,eng,2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,29221,2153167,0439358078,9780439358071,870,eng,2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,244,6333,0439554896,9780439554893,352,eng,2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,36325,2339585,043965548X,9780439655484,435,eng,2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,164,41428,0439682584,9780439682589,2690,eng,2004,Scholastic

In [118]:
df = df.reset_index(drop=True)

In [119]:
df

,Book_ID,Book_Title,Authors,Rating,Number_of_reviews,Ratings_Count,ISBN-10,ISBN-13,Num_Of_Pages,Language_Code,Publication_year,Publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,27591,2095690,0439785960,9780439785969,652,eng,2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,29221,2153167,0439358078,9780439358071,870,eng,2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,244,6333,0439554896,9780439554893,352,eng,2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,36325,2339585,043965548X,9780439655484,435,eng,2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,164,41428,0439682584,9780439682589,2690,eng,2004,Scholastic
...,...,...,...,...,...,...,...,...,...,...,...,...
10341,45631,Expelled from Eden: A William T. Vollmann Reader,William T. Vollmann/Larry McCaffery/Michael He...,4.06,20,156,1560254416,9781560254416,512,eng,2004,Da Capo Press
10342,45633,You Bright and Risen Angels,William T. Vollmann,4.08,56,783,0140110879,9780140110876,635,eng,1988,Penguin Books
10343,45634,The Ice-Shirt (Seven Dreams #1),William T. Vollmann,3.96,95,820,0140131965,9780140131963,415,eng,1993,Penguin Books
10344,45639,Poor People,William T. Vollmann,3.72,139,769,0060878827,9780060878825,434,eng,2007,Ecco
10345,45641,Las aventuras de Tom Sawyer,Mark Twain,3.91,12,113,8497646983,9788497646987,272,spa,2006,Edimat Libros

In [121]:
df.columns

Index(['Book_ID', 'Book_Title', 'Authors', 'Rating', 'Number_of_reviews',
       'Ratings_Count', 'ISBN-10', 'ISBN-13', 'Num_Of_Pages', 'Language_Code',
       'Publication_year', 'Publisher'],
      dtype='object')

In [123]:
df.to_csv("clean_Book.csv",index=False)